export type TeamInfo = { city: string };
export const TEAM_CITY: Record<string, TeamInfo> = {
  "Arizona Cardinals": { city: "Glendale, AZ" },
  "Atlanta Falcons": { city: "Atlanta, GA" },
  "Baltimore Ravens": { city: "Baltimore, MD" },
  "Buffalo Bills": { city: "Orchard Park, NY" },
  "Carolina Panthers": { city: "Charlotte, NC" },
  "Chicago Bears": { city: "Chicago, IL" },
  "Cincinnati Bengals": { city: "Cincinnati, OH" },
  "Cleveland Browns": { city: "Cleveland, OH" },
  "Dallas Cowboys": { city: "Arlington, TX" },
  "Denver Broncos": { city: "Denver, CO" },
  "Detroit Lions": { city: "Detroit, MI" },
  "Green Bay Packers": { city: "Green Bay, WI" },
  "Houston Texans": { city: "Houston, TX" },
  "Indianapolis Colts": { city: "Indianapolis, IN" },
  "Jacksonville Jaguars": { city: "Jacksonville, FL" },
  "Kansas City Chiefs": { city: "Kansas City, MO" },
  "Las Vegas Raiders": { city: "Paradise, NV" },
  "Los Angeles Chargers": { city: "Inglewood, CA" },
  "Los Angeles Rams": { city: "Inglewood, CA" },
  "Miami Dolphins": { city: "Miami Gardens, FL" },
  "Minnesota Vikings": { city: "Minneapolis, MN" },
  "New England Patriots": { city: "Foxborough, MA" },
  "New Orleans Saints": { city: "New Orleans, LA" },
  "New York Giants": { city: "East Rutherford, NJ" },
  "New York Jets": { city: "East Rutherford, NJ" },
  "Philadelphia Eagles": { city: "Philadelphia, PA" },
  "Pittsburgh Steelers": { city: "Pittsburgh, PA" },
  "San Francisco 49ers": { city: "Santa Clara, CA" },
  "Seattle Seahawks": { city: "Seattle, WA" },
  "Tampa Bay Buccaneers": { city: "Tampa, FL" },
  "Tennessee Titans": { city: "Nashville, TN" },
  "Washington Commanders": { city: "Landover, MD" }
};

